version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db


  db:
    image: mysql:5.7
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${TYPEORM_DATABASE}
      - MYSQL_USER=${TYPEORM_USERNAME}
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
      - TZ=America/Sao_Paulo
    volumes:
      - .docker/dbdata:/var/lib/mysql
